apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: broken-app-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: broken-app
    rules:
    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total{namespace="sre-demo"}[5m]) > 0
      for: 1m
      labels:
        severity: critical
        slo_impact: high
      annotations:
        summary: "Pod {{ $labels.pod }} is crash looping"
        action: restart_pod

    - alert: PodOOMKilled
      expr: kube_pod_container_status_last_terminated_reason{namespace="sre-demo", reason="OOMKilled"} == 1
      for: 1m
      labels:
        severity: critical
        slo_impact: high
      annotations:
        summary: "Pod {{ $labels.pod }} was OOMKilled"
        action: scale_up

    - alert: PodNotReady
      expr: kube_pod_status_ready{namespace="sre-demo", condition="true"} == 0
      for: 2m
      labels:
        severity: warning
        slo_impact: medium
      annotations:
        summary: "Pod {{ $labels.pod }} is not ready"
        action: restart_pod
