apiVersion: v1
kind: Service
metadata:
  name: broken-app
  namespace: sre-demo
spec:
  selector:
    app: broken-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
  type: NodePort
